apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simplenodejsappdeployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: simplenodejsapp
    spec:
      containers:
      - name: simplenodejsapp
        image: hectagonacr.azurecr.io/simplenodejsapp:latest
        env:
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            valueFrom:
              secretKeyRef:
                name: simple-nodejs-app-insights-key
                key: key
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: azurecontainerreg