apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-nodejs-app-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: simple-nodejs-app
    spec:
      containers:
      - name: simple-nodejs-app
        image: hectagonacr.azurecr.io/simple-nodejs-app:2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      