apiVersion: v1
kind: Service
metadata:
  name: simplenodejsappsvc
  labels:
    version: test
spec:
  selector:
    app: simplenodejsapp
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer