apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-app-svc
  labels:
    version: test
spec:
  selector:
    app: simple-nodejs-app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer